# Workflow will:
# - install Golang dependencies;
# - lint and run tests with multiple Golang versions.
# For more information see:
# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-go

name: test_application

on:
  workflow_call:
    inputs:
      app_name:
        type: string
        required: true
        description: Application and source code folder name
      ci_image:
        type: string
        required: false
        default: ubuntu-22.04
        description: Github type of machine to run the workflow on
      go_versions:
        type: string
        required: false
        default: "['1.20','1.22','1.23']"
        description: Golang versions to build workflow matrix
      lint:
        type: boolean
        required: false
        default: true
        description: Whether to lint application
      test:
        type: boolean
        required: false
        default: true
        description: Whether to test application

jobs:
  golang:
    name: Test App
    runs-on: ${{ inputs.ci_image }}
    env:
      APP: ${{ inputs.app_name }}
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJSON(inputs.go_versions) }}

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history

    - name: Git Version
      id: version
      uses: codacy/git-version@2.8.0
      with:
        release-branch: ${{ github.event.repository.default_branch }}

    - name: Set variables
      if: success()
      id: prepare
      shell: bash
      run: |
        echo version="${TAG%%-*}" >> "$GITHUB_OUTPUT"
      env:
        TAG: ${{ steps.version.outputs.version }}

    - name: Set up Golang ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Load cached dependencies
      id: cached-dependencies
      uses: actions/cache@v4
      with:
        path: ./go.sum
        key: ${{ runner.os }}-venv-golang${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}

    - name: Install dependencies
      if: steps.cached-dependencies.outputs.cache-hit != 'true'
      run: |
        make test_setup

    - name: Lint
      if: ${{ inputs.lint }}
      run: |
        make lint

    - name: Format
      if: ${{ inputs.lint }}
      run: |
        make format

    - name: Test
      if: ${{ inputs.test }}
      run: |
        make test
